<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#OPERACIONES-CON-COLUMNAS-O-FILAS" data-toc-modified-id="OPERACIONES-CON-COLUMNAS-O-FILAS-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>OPERACIONES CON COLUMNAS O FILAS</a></span><ul class="toc-item"><li><span><a href="#Multiplicar-una-columna-por-un-número" data-toc-modified-id="Multiplicar-una-columna-por-un-número-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Multiplicar una columna por un número</a></span></li><li><span><a href="#Suma-o-resta-de-columnas" data-toc-modified-id="Suma-o-resta-de-columnas-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Suma o resta de columnas</a></span></li><li><span><a href="#Multiplicación-y-División-de-columnas" data-toc-modified-id="Multiplicación-y-División-de-columnas-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Multiplicación y División de columnas</a></span></li><li><span><a href="#Potencia-pow(elemento,-potencia)" data-toc-modified-id="Potencia-pow(elemento,-potencia)-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Potencia pow(elemento, potencia)</a></span></li><li><span><a href="#Exponencial" data-toc-modified-id="Exponencial-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Exponencial</a></span></li></ul></li><li><span><a href="#Eliminar-columnas-con-drop" data-toc-modified-id="Eliminar-columnas-con-drop-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Eliminar columnas con drop</a></span></li><li><span><a href="#Filtros-en-Pandas" data-toc-modified-id="Filtros-en-Pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Filtros en Pandas</a></span></li><li><span><a href="#FORMAS-DE-ORDENAR" data-toc-modified-id="FORMAS-DE-ORDENAR-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>FORMAS DE ORDENAR</a></span><ul class="toc-item"><li><span><a href="#Ordenando-las-filas-por-los-valores-de-una-columna" data-toc-modified-id="Ordenando-las-filas-por-los-valores-de-una-columna-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Ordenando las filas por los valores de una columna</a></span></li><li><span><a href="#Ordenando-las-filas-por-los-valores-de-varias-columnas:" data-toc-modified-id="Ordenando-las-filas-por-los-valores-de-varias-columnas:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Ordenando las filas por los valores de varias columnas:</a></span></li></ul></li></ul></div>

![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
# Situación Profesional 2
# Clase 3: Pandas
**Prof. Ricardo Piña**

In [1]:
import pandas as pd
import numpy as np

## OPERACIONES CON COLUMNAS O FILAS

Carguemos el archivo csv iris.tab en un dataframe de nombre df_iris

In [2]:
df_iris=pd.read_csv("data/iris.tab",sep='\t',skiprows=(1,2))
df_iris.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/iris.tab'

Cambie los nombres para que no tengan espacios ...

In [ ]:
# Escriba aquí su código
df_iris.columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'iris']

In [ ]:
df_iris.info()

### Multiplicar una columna por un número

Supongamos que necesitamos multiplicar por 2 la columna sepal_length, entonces simplemente hacemos:  
columna * 2

In [ ]:
df_iris.sepal_length*2

Compare con la impresión del dataframe que hicimos antes y podrá verificar que los valores de la columna efectivamente han sido multiplicados por 2, **aunque estos cambios no sea han efectuado en el dataframe**, fijese:

In [ ]:
df_iris.head()

Si quisiéramos que se cambiara la columna, deberíamos asignarle el resultado obtenido. En este caso no deseamos hacerlo.

### Suma o resta de columnas

**columna + columna**  
**columna - columna**

Supongamos que necesitamos restar sepal_length - petal_length, simplemente podemos hacer lo siguiente:

In [ ]:
df_iris.sepal_length - df_iris.petal_length

De la misma manera que indicábamos con anterioridad, este resultado no se encuentra en el dataframe.   
Esta vez sí supongamos que deseamos **agregarlo** como una columna más del dataframe con el nombre de 'sl-pl'.

In [ ]:
df_iris['sl-pl']=df_iris.sepal_length - df_iris.petal_length
df_iris

### Multiplicación y División de columnas

**columna * columna**
**columna/columna**

En un caso como el del reconocimiento de la flor Iris por Machine Learning, seguramente sería de interés tener en una feature o variable con una aproximación a la superficie de los pétalos.  

Agregue esta columna con el nombre 'sup-pet'

In [5]:
# Escriba aquí su código
df_iris["sup-pet"]=df_iris.petal_length * df_iris.petal_width
df_iris

NameError: name 'df_iris' is not defined

Podríamos hacer lo mismo para los sépalos .. guárdelo en la columna 'sup-sep'

In [10]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,3.5,0.28,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,3.6,0.28,18.00

Seguro que un problema de identificación de flores de las cuales conocemos las medidas, las relaciones entre las medidas también sería importantes, así que creemos una nueva variable llamada 'pet_l/pet_w' cuyos valores sean  la división de petal_length sobre petal_width.

In [11]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,3.5,0.28,14.70,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,3.6,0.28,18.00,7.0

### Potencia pow(elemento, potencia)
También podríamos elevar al cuadrado, al cubo o a la n los valores de alguna columna ...

Eleve al cuadrado los valores de petal_length, no los agregue al dataframe.

In [12]:
pow(df_iris.petal_length,2)

0       1.96
1       1.96
2       1.69
3       2.25
4       1.96
       ...
145    27.04
146    25.00
147    27.04
148    29.16
149    26.01
Name: petal_length, Length: 150, dtype: float64

In [13]:
df_iris.petal_length**2

0       1.96
1       1.96
2       1.69
3       2.25
4       1.96
       ...
145    27.04
146    25.00
147    27.04
148    29.16
149    26.01
Name: petal_length, Length: 150, dtype: float64

Las raíces también pueden calcularse como potencia.

### Exponencial 
$$ e^c $$

Daría por resultado cada elemento de la columna como exponente de e.

In [14]:
np.exp(df_iris.petal_length)   # tuve que usar np.exp() porque de otra manera no me andaba, verifique.

0        4.055200
1        4.055200
2        3.669297
3        4.481689
4        4.055200
          ...
145    181.272242
146    148.413159
147    181.272242
148    221.406416
149    164.021907
Name: petal_length, Length: 150, dtype: float64

## Eliminar columnas con drop

Supongamos que queremos eliminar la columna sl-pl que creamos hacer un rato, podemos usar .drop:

documentación en: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [15]:
df_iris.drop('sl-pl',axis=1).head() # axis=1 para eliminar la columna.

# también se podría haber usado:
# df_iris.drop(columns=['sl-pl'])  y evitamos recordar el axis!

,sepal_length,sepal_width,petal_length,petal_width,iris,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,0.28,17.85,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,0.28,14.70,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,0.26,15.04,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,0.30,14.26,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,0.28,18.00,7.0

## Filtros en Pandas

Los filtros de tipo **.filter** en Pandas **NO** se usan para filtrar por el valor de los ítems (las celdas de Excel), sino que se utilizan para **filtrar por los valores o etiquetas de los índices de las columnas o de las filas**. No los veremos por el momento. 

Documentación: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.filter.html

Nuestro interés está en el proceso de **filtrado por valores de los items** y en este sentido es muy similar al funcionamiento de NumPy.  

En la jerga de Pandas en vez de filtrado se suele denominar como  

*__obtención de subconjuntos de filas que, por ejemplo, verifican cierto criterio__*.

Recordemos qué tenemos en nuestro dataframe:

In [16]:
df_iris.head()

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,3.5,0.28,14.70,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,3.6,0.28,18.00,7.0

Supongamos que deseamos ver todas las filas para las cuales el valor de sepal_length sea menor que 5.  
El procedimiento será muy similar al del NumPy.

In [17]:
df_iris[df_iris.sepal_length < 5]

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
1,4.9,3.0,1.4,0.2,Iris-setosa,3.5,0.28,14.70,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.500000
6,4.6,3.4,1.4,0.3,Iris-setosa,3.2,0.42,15.64,4.666667
8,4.4,2.9,1.4,0.2,Iris-setosa,3.0,0.28,12.76,7.000000
9,4.9,3.1,1.5,0.1,Iris-setosa,3.4,0.15,15.19,15.000000
11,4.8,3.4,1.6,0.2,Iris-setosa,3.2,0.32,16.32,8.000000
12,4.8,3.0,1.4,0.1,Iris-setosa,3.4,0.14,14.40,14.000000
13,4.3,3.0,1.1,0.1,Iris-setosa,3.2,0.11,12.90,11.000000
22,4.6,3.6,1.0,0.2,Iris-setosa,3.6,0.20,16.56,5.000000
24,4.8,3.4,1.9,0.2,Iris-setosa,2.9,0.38,16.32,9.500000
29,4.7,3.2,1.6,0.2,Iris-setosa,3.1,0.32,15.04,8.000000
30,4.8,3.1,1.6,0.2,Iris-setosa,3.2,0.32,14.88,8.000000
34,4.9,3.1,1.5,0.1,Iris-setosa,3.4,0.15,15.19,15.000000
37,4.9,3.1,1.5,0.1,Iris-setosa,3.4,0.15,15.19,15.000000
38,4.4,3.0,1.3,0.2,Iris-setosa,3.1,0.26,13.20,6.500000
41,4.5,2.3,1.3,0.3,Iris-setosa,3.2,0.39,10.35,4.333333
42,4.4,3.2,1.3,0.2,Iris-setosa,3.1,0.26,14.08,6.500000
45,4.8,3.0,1.4,0.3,Iris-setosa,3.4,0.42,14.40,4.666667
47,4.6,3.2,1.4,0.2,Iris-setosa,3.2,0.28,14.72,7.000000
57,4.9,2.4,3.3,1.0,Iris-versicolor,1.6,3.30,11.76,3.300000
106,4.9,2.5,4.5,1.7,Iris-virginica,0.4,7.65,12.25,2.647059

Obtengamos las filas para las cuales el valor de sepal_length sea mayor que el doble del sepal_width

In [18]:
#Escriba aqui su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
50,7.0,3.2,4.7,1.4,Iris-versicolor,2.3,6.58,22.40,3.357143
52,6.9,3.1,4.9,1.5,Iris-versicolor,2.0,7.35,21.39,3.266667
53,5.5,2.3,4.0,1.3,Iris-versicolor,1.5,5.20,12.65,3.076923
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
55,5.7,2.8,4.5,1.3,Iris-versicolor,1.2,5.85,15.96,3.461538
...,...,...,...,...,...,...,...,...,...
143,6.8,3.2,5.9,2.3,Iris-virginica,0.9,13.57,21.76,2.565217
144,6.7,3.3,5.7,2.5,Iris-virginica,1.0,14.25,22.11,2.280000
145,6.7,3.0,5.2,2.3,Iris-virginica,1.5,11.96,20.10,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,1.3,9.50,15.75,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,1.3,10.40,19.50,2.600000

Lo mismo que antes pero muestre sólo esas dos columnas y la columna iris

In [19]:
# Escriba aqui su código

     sepal_length  sepal_width             iris
50            7.0          3.2  Iris-versicolor
52            6.9          3.1  Iris-versicolor
53            5.5          2.3  Iris-versicolor
54            6.5          2.8  Iris-versicolor
55            5.7          2.8  Iris-versicolor
..            ...          ...              ...
143           6.8          3.2   Iris-virginica
144           6.7          3.3   Iris-virginica
145           6.7          3.0   Iris-virginica
146           6.3          2.5   Iris-virginica
147           6.5          3.0   Iris-virginica

[79 rows x 3 columns]

Muestre qué valores **distintos** se han cargado en la columna iris.

In [20]:
#Escriba aquí su código

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

Queremos todas las filas para las cuales en la columna iris dice Iris-virginica. Muestre sólo las primeras 4

In [21]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
100,6.3,3.3,6.0,2.5,Iris-virginica,0.3,15.00,20.79,2.400000
101,5.8,2.7,5.1,1.9,Iris-virginica,0.7,9.69,15.66,2.684211
102,7.1,3.0,5.9,2.1,Iris-virginica,1.2,12.39,21.30,2.809524
103,6.3,2.9,5.6,1.8,Iris-virginica,0.7,10.08,18.27,3.111111

Cuando tenemos valores de cadena de texto suele ser útil el uso de:  

**columna.str.contains('cadena_de_caracteres')**   

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v.

In [45]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
50,7.0,3.2,4.7,1.4,Iris-versicolor,2.3,6.58,22.40,3.357143
51,6.4,3.2,4.5,1.5,Iris-versicolor,1.9,6.75,20.48,3.000000
52,6.9,3.1,4.9,1.5,Iris-versicolor,2.0,7.35,21.39,3.266667
53,5.5,2.3,4.0,1.3,Iris-versicolor,1.5,5.20,12.65,3.076923
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,1.5,11.96,20.10,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,1.3,9.50,15.75,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,1.3,10.40,19.50,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,0.8,12.42,21.08,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,0.8,9.18,17.70,2.833333

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v y contiene la cadena 'color'

In [44]:
df_iris[(df_iris.iris.str.contains('v')) & (df_iris.iris.str.contains('color'))]  # con and nos dio error

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
50,7.0,3.2,4.7,1.4,Iris-versicolor,2.3,6.58,22.40,3.357143
51,6.4,3.2,4.5,1.5,Iris-versicolor,1.9,6.75,20.48,3.000000
52,6.9,3.1,4.9,1.5,Iris-versicolor,2.0,7.35,21.39,3.266667
53,5.5,2.3,4.0,1.3,Iris-versicolor,1.5,5.20,12.65,3.076923
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
55,5.7,2.8,4.5,1.3,Iris-versicolor,1.2,5.85,15.96,3.461538
56,6.3,3.3,4.7,1.6,Iris-versicolor,1.6,7.52,20.79,2.937500
57,4.9,2.4,3.3,1.0,Iris-versicolor,1.6,3.30,11.76,3.300000
58,6.6,2.9,4.6,1.3,Iris-versicolor,2.0,5.98,19.14,3.538462
59,5.2,2.7,3.9,1.4,Iris-versicolor,1.3,5.46,14.04,2.785714
60,5.0,2.0,3.5,1.0,Iris-versicolor,1.5,3.50,10.00,3.500000
61,5.9,3.0,4.2,1.5,Iris-versicolor,1.7,6.30,17.70,2.800000
62,6.0,2.2,4.0,1.0,Iris-versicolor,2.0,4.00,13.20,4.000000
63,6.1,2.9,4.7,1.4,Iris-versicolor,1.4,6.58,17.69,3.357143
64,5.6,2.9,3.6,1.3,Iris-versicolor,2.0,4.68,16.24,2.769231
65,6.7,3.1,4.4,1.4,Iris-versicolor,2.3,6.16,20.77,3.142857
66,5.6,3.0,4.5,1.5,Iris-versicolor,1.1,6.75,16.80,3.000000
67,5.8,2.7,4.1,1.0,Iris-versicolor,1.7,4.10,15.66,4.100000
68,6.2,2.2,4.5,1.5,Iris-versicolor,1.7,6.75,13.64,3.000000
69,5.6,2.5,3.9,1.1,Iris-versicolor,1.7,4.29,14.00,3.545455
70,5.9,3.2,4.8,1.8,Iris-versicolor,1.1,8.64,18.88,2.666667
71,6.1,2.8,4.0,1.3,Iris-versicolor,2.1,5.20,17.08,3.076923
72,6.3,2.5,4.9,1.5,Iris-versicolor,1.4,7.35,15.75,3.266667
73,6.1,2.8,4.7,1.2,Iris-versicolor,1.4,5.64,17.08,3.916667
74,6.4,2.9,4.3,1.3,Iris-versicolor,2.1,5.59,18.56,3.307692
75,6.6,3.0,4.4,1.4,Iris-versicolor,2.2,6.16,19.80,3.142857
76,6.8,2.8,4.8,1.4,Iris-versicolor,2.0,6.72,19.04,3.428571
77,6.7,3.0,5.0,1.7,Iris-versicolor,1.7,8.50,20.10,2.941176
78,6.0,2.9,4.5,1.5,Iris-versicolor,1.5,6.75,17.40,3.000000
79,5.7,2.6,3.5,1.0,Iris-versicolor,2.2,3.50,14.82,3.500000
80,5.5,2.4,3.8,1.1,Iris-versicolor,1.7,4.18,13.20,3.454545
81,5.5,2.4,3.7,1.0,Iris-versicolor,1.8,3.70,13.20,3.700000
82,5.8,2.7,3.9,1.2,Iris-versicolor,1.9,4.68,15.66,3.250000
83,6.0,2.7,5.1,1.6,Iris-versicolor,0.9,8.16,16.20,3.187500
84,5.4,3.0,4.5,1.5,Iris-versicolor,0.9,6.75,16.20,3.000000
85,6.0,3.4,4.5,1.6,Iris-versicolor,1.5,7.20,20.40,2.812500
86,6.7,3.1,4.7,1.5,Iris-versicolor,2.0,7.05,20.77,3.133333
87,6.3,2.3,4.4,1.3,Iris-versicolor,1.9,5.72,14.49,3.384615
88,5.6,3.0,4.1,1.3,Iris-versicolor,1.5,5.33,16.80,3.153846
89,5.5,2.5,4.0,1.3,Iris-versicolor,1.5,5.20,13.75,3.076923
90,5.5,2.6,4.4,1.2,Iris-versicolor,1.1,5.28,14.30,3.666667
91,6.1,3.0,4.6,1.4,Iris-versicolor,1.5,6.44,18.30,3.285714
92,5.8,2.6,4.0,1.2,Iris-versicolor,1.8,4.80,15.08,3.333333
93,5.0,2.3,3.3,1.0,Iris-versicolor,1.7,3.30,11.50,3.300000
94,5.6,2.7,4.2,1.3,Iris-versicolor,1.4,5.46,15.12,3.230769
95,5.7,3.0,4.2,1.2,Iris-versicolor,1.5,5.04,17.10,3.500000
96,5.7,2.9,4.2,1.3,Iris-versicolor,1.5,5.46,16.53,3.230769
97,6.2,2.9,4.3,1.3,Iris-versicolor,1.9,5.59,17.98,3.307692
98,5.1,2.5,3.0,1.1,Iris-versicolor,2.1,3.30,12.75,2.727273
99,5.7,2.8,4.1,1.3,Iris-versicolor,1.6,5.33,15.96,3.153846

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v o  contiene la cadena 'color'.

In [43]:
df_iris[(df_iris.iris.str.contains('v')) | (df_iris.iris.str.contains('color'))]  # con or nos dio error

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
50,7.0,3.2,4.7,1.4,Iris-versicolor,2.3,6.58,22.40,3.357143
51,6.4,3.2,4.5,1.5,Iris-versicolor,1.9,6.75,20.48,3.000000
52,6.9,3.1,4.9,1.5,Iris-versicolor,2.0,7.35,21.39,3.266667
53,5.5,2.3,4.0,1.3,Iris-versicolor,1.5,5.20,12.65,3.076923
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,1.5,11.96,20.10,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,1.3,9.50,15.75,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,1.3,10.40,19.50,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,0.8,12.42,21.08,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,0.8,9.18,17.70,2.833333

Obviamente que   
**columna.str.contains('cadena_de_caracteres')**  

puede usarse con más de una caracter. En este caso buscará la cadena en cualquier parte del texto que figure en cada una de las celdas de esa columna. 

Si necesitamos una expresión más exacta, podemos usar **regex**, que tiene sus complicaciones, pero por ahora no entraremos en esos detalles.

Queremos todas las filas en las cuales el valor de iris contenga la cadena 'color'. Muestre sólo los últimos 4 registros

In [23]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
96,5.7,2.9,4.2,1.3,Iris-versicolor,1.5,5.46,16.53,3.230769
97,6.2,2.9,4.3,1.3,Iris-versicolor,1.9,5.59,17.98,3.307692
98,5.1,2.5,3.0,1.1,Iris-versicolor,2.1,3.30,12.75,2.727273
99,5.7,2.8,4.1,1.3,Iris-versicolor,1.6,5.33,15.96,3.153846

Queremos todas las filas cuyo texto en la columna iris no contenga la cadena *color*. Muestre las últimas 3 filsa.  

**Nota:** no existe el método "notcontains", asi que podría usar la idea de  negar el resultado de contains. Puede hacerlo de dos maneras usando **~** que es el operador para __negación__, o bien imponiendo en la condición que el resultado de contains()==False.

In [24]:
df_iris[ ~df_iris.iris.str.contains('color')].tail(3)

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
147,6.5,3.0,5.2,2.0,Iris-virginica,1.3,10.40,19.50,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,0.8,12.42,21.08,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,0.8,9.18,17.70,2.833333

Queremos todas las filas para las cuales sepal_length es mayor a 4, petal_lenght menor a 3 y el texto cargado en iris no contiene la cadena color. Muestre las primeras 6 filas.   


Nota: use & para la operación lógica y en vez de and, suele ser necesario separar las pruebas lógicas escribiéndolas entre paréntesis.

In [25]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.00
1,4.9,3.0,1.4,0.2,Iris-setosa,3.5,0.28,14.70,7.00
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04,6.50
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.50
4,5.0,3.6,1.4,0.2,Iris-setosa,3.6,0.28,18.00,7.00
5,5.4,3.9,1.7,0.4,Iris-setosa,3.7,0.68,21.06,4.25

En la primer clase de Pandas vimos cómo calcular la media de los valores de una columna.

En qué observaciones el valor de sepal_length está por sobre la media? Muestre las 5 primeras filas.

In [26]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
50,7.0,3.2,4.7,1.4,Iris-versicolor,2.3,6.58,22.40,3.357143
51,6.4,3.2,4.5,1.5,Iris-versicolor,1.9,6.75,20.48,3.000000
52,6.9,3.1,4.9,1.5,Iris-versicolor,2.0,7.35,21.39,3.266667
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
56,6.3,3.3,4.7,1.6,Iris-versicolor,1.6,7.52,20.79,2.937500

Ahora queremos ver todas las filas para las cuales el valor de sepal_length está por sobre la media y los valores de sepal_width están por debajo de la media.

In [47]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
54,6.5,2.8,4.6,1.5,Iris-versicolor,1.9,6.90,18.20,3.066667
58,6.6,2.9,4.6,1.3,Iris-versicolor,2.0,5.98,19.14,3.538462
61,5.9,3.0,4.2,1.5,Iris-versicolor,1.7,6.30,17.70,2.800000
62,6.0,2.2,4.0,1.0,Iris-versicolor,2.0,4.00,13.20,4.000000
63,6.1,2.9,4.7,1.4,Iris-versicolor,1.4,6.58,17.69,3.357143

Ahora queremos las filas en las cuales la media de sepal_length **o** la media de sepal_width están por sobre sus respectivas medias.

In [28]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.00
2,4.7,3.2,1.3,0.2,Iris-setosa,3.4,0.26,15.04,6.50
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.50
4,5.0,3.6,1.4,0.2,Iris-setosa,3.6,0.28,18.00,7.00
5,5.4,3.9,1.7,0.4,Iris-setosa,3.7,0.68,21.06,4.25

## FORMAS DE ORDENAR

### Ordenando las filas por los valores de una columna

Si queremos ordenar el dataframe por los valores de una fila, podemos usar:  

**DataFrame.sort_values()** 

Documentación: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

En este caso es interesante observar sus argumentos, véalos en la documentación indicada.

Obtengamos un duplicado de df_iris, de tal forma que sus filas estén ordenadas por las columna iris en formas ascendente, es decir de a a la z.

In [49]:
df_iris.sort_values('iris')

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.000000
27,5.2,3.5,1.5,0.2,Iris-setosa,3.7,0.30,18.20,7.500000
28,5.2,3.4,1.4,0.2,Iris-setosa,3.8,0.28,17.68,7.000000
29,4.7,3.2,1.6,0.2,Iris-setosa,3.1,0.32,15.04,8.000000
30,4.8,3.1,1.6,0.2,Iris-setosa,3.2,0.32,14.88,8.000000
...,...,...,...,...,...,...,...,...,...
119,6.0,2.2,5.0,1.5,Iris-virginica,1.0,7.50,13.20,3.333333
120,6.9,3.2,5.7,2.3,Iris-virginica,1.2,13.11,22.08,2.478261
121,5.6,2.8,4.9,2.0,Iris-virginica,0.7,9.80,15.68,2.450000
111,6.4,2.7,5.3,1.9,Iris-virginica,1.1,10.07,17.28,2.789474
149,5.9,3.0,5.1,1.8,Iris-virginica,0.8,9.18,17.70,2.833333

Obtengamos un duplicado de df_iris, de tal forma que sus filas estén ordenadas por las columna iris en formas descendente, es decir de la z a la a.

In [30]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
149,5.9,3.0,5.1,1.8,Iris-virginica,0.8,9.18,17.70,2.833333
111,6.4,2.7,5.3,1.9,Iris-virginica,1.1,10.07,17.28,2.789474
122,7.7,2.8,6.7,2.0,Iris-virginica,1.0,13.40,21.56,3.350000
121,5.6,2.8,4.9,2.0,Iris-virginica,0.7,9.80,15.68,2.450000
120,6.9,3.2,5.7,2.3,Iris-virginica,1.2,13.11,22.08,2.478261
...,...,...,...,...,...,...,...,...,...
31,5.4,3.4,1.5,0.4,Iris-setosa,3.9,0.60,18.36,3.750000
30,4.8,3.1,1.6,0.2,Iris-setosa,3.2,0.32,14.88,8.000000
29,4.7,3.2,1.6,0.2,Iris-setosa,3.1,0.32,15.04,8.000000
28,5.2,3.4,1.4,0.2,Iris-setosa,3.8,0.28,17.68,7.000000
0,5.1,3.5,1.4,0.2,Iris-setosa,3.7,0.28,17.85,7.000000

### Ordenando las filas por los valores de varias columnas:

Cuando se ordena por los valores de varias columnas es importante tener en cuenta qué significa.  
Supongamos que tenemos un df con las columnas Apellido y Nombre y asumamos que queremos ordenarla por las columnas Apellido (primero) y (luego por ) las columna nombre.  

Esto significa que el ordenamiento principal será por Apellido y en el caso que "haya empate" en el valor del apellido, entonces desempatará con el valor de la columna Nombre.

Ordenar en forma ascentente a df_iris primero por la columna iris y luego por la columna sepal_length. Muestre los primero 6 casos. En este caso, cuando tenemos varias columnas para ordenar, debemos pasar los valores de las columnas como array.

In [50]:

df_iris.sort_values(by=[ 'iris','sepal_length']).head(6)

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
13,4.3,3.0,1.1,0.1,Iris-setosa,3.2,0.11,12.90,11.000000
8,4.4,2.9,1.4,0.2,Iris-setosa,3.0,0.28,12.76,7.000000
38,4.4,3.0,1.3,0.2,Iris-setosa,3.1,0.26,13.20,6.500000
42,4.4,3.2,1.3,0.2,Iris-setosa,3.1,0.26,14.08,6.500000
41,4.5,2.3,1.3,0.3,Iris-setosa,3.2,0.39,10.35,4.333333
3,4.6,3.1,1.5,0.2,Iris-setosa,3.1,0.30,14.26,7.500000

Ahora ordene por las columnas iris, sepal_length y sepal_width, en ese orden.

In [32]:
# Escriba aquí su código

Qué pasará si queremos ordenar por una columna en forma ascendente y por otra en forma descendente?  
Ayuda, de la misma manera que podemos pasar varias columnas en un array, también podemos hacer lo mismo para el valor del  atributo **ascending** ... 

Ordene df_iris primero por la columna iris en forma descendente y luego por la columna sepal_length en forma ascendente. Muestre las 6 primeras filas.

In [33]:
# Escriba aquí su código

,sepal_length,sepal_width,petal_length,petal_width,iris,sl-pl,sup-pet,sup-sep,pet_l/pet_w
106,4.9,2.5,4.5,1.7,Iris-virginica,0.4,7.65,12.25,2.647059
121,5.6,2.8,4.9,2.0,Iris-virginica,0.7,9.80,15.68,2.450000
113,5.7,2.5,5.0,2.0,Iris-virginica,0.7,10.00,14.25,2.500000
101,5.8,2.7,5.1,1.9,Iris-virginica,0.7,9.69,15.66,2.684211
114,5.8,2.8,5.1,2.4,Iris-virginica,0.7,12.24,16.24,2.125000
142,5.8,2.7,5.1,1.9,Iris-virginica,0.7,9.69,15.66,2.684211